### ISSUE TITLE
Conditional Path ???

### ISSUE THREAD

**Issue by debugDS** [cliffrowley/atom-open-in-sourcetree#1]
In OSX it starts Sourcetree in Parallels Desktop.
I added /Applications/SourceTree.app in line 9 in file open-in-sourcetree.coffee

Tx

**Comment by cliffrowley** [comment]
Thanks, we'll fix this.  In future would you mind creating a pull request?  It just makes it a bit easier to squeeze things like this in between work tasks - thanks!

**Comment by debugDS** [comment]
Ok I'll do that next time.

Tx

**Comment by cliffrowley** [comment]
@debugDS I'll push an update to npm shortly, once I've done that if you could tell me whether this fixes the issue that'd be great.  Thanks!

**Comment by debugDS** [comment]
Sorry for the delay.
It's working fine
Tx
