### ISSUE TITLE
Uncaught TypeError: string.indexOf is not a function

### ISSUE THREAD

**Issue by a7madgamal** [cliffrowley/atom-open-in-sourcetree#12]
when I have multiple projects added to the same window
/Users/mido/.atom/packages/open-in-sourcetree/node_modules/fuzzaldrin/lib/scorer.js:60
Hide Stack Trace
TypeError: string.indexOf is not a function
    at Object.exports.score (open-in-sourcetree/node_modules/fuzzaldrin/lib/scorer.js:60:31)
    at module.exports (open-in-sourcetree/node_modules/fuzzaldrin/lib/filter.js:25:24)
    at filter (open-in-sourcetree/node_modules/fuzzaldrin/lib/fuzzaldrin.js:21:14)
    at ProjectPathListView.module.exports.SelectListView.populateList packages/open-in-sourcetree/node_modules/atom-space-pen-views/lib/select-list-view.js:195:25)
    at open-in-sourcetree/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26

**Comment by cliffrowley** [comment]
Interesting.  I don't use multiple projects typically, but it's definitely something this plugin should support.

Are you au fait with Atom and its internals?  Are you able to fix and submit a PR?
—
Cliff Rowley
Thinker, Tinkerer, Dork
@cliffrowley

**Comment by a7madgamal** [comment]
Sorry I missed your reply.
#11 I think this is also the same thing.
I'm afraid I'm not that good yet with atom :(

**Comment by cliffrowley** [comment]
No worries, I will get around to look at this as soon as I can.  I've been busy lately and I'm full to the eyeballs with a horrible cold at the moment so coding is the last thing I feel like doing..  Give me a few days and I'll get a look.

**Comment by a7madgamal** [comment]
tyt and I hope you get better soon 🤒

**Comment by a7madgamal** [comment]
@cliffrowley 👍 
I hope you get rid of the popup completely and just open the active file's project directly
or what do you think?

**Comment by kachkaev** [comment]
I was able to fix this in #14 🎉 ! Thanks @a7madgamal for reporting this issue – it was reassuring to know that I was not alone!

@cliffrowley hope to see the fix in a new release of your package. Thanks a lot for implementing `atom-open-in-sourcetree` – it's exactly what I was looking for!

**Comment by cliffrowley** [comment]
Hi @kachkaev - I don't actually use Atom at the moment, would you be interested in becoming a collaborator for this extension?

**Comment by kachkaev** [comment]
Yep, I don’t mind, thanks. Have you switched to vscode? :–)

In any case, could you please publish a new version on npm once it’s been cut?

**Comment by kachkaev** [comment]
Thanks for adding me as a collaborator @cliffrowley! I'll prepare `0.1.9` now <s>so you'll only need to pull the latest commits, check them and `apm publish` 👍 </s>

---
<s>__UPD:__ Done with preparing 0.1.9! 🎉</s>

Hmm.. Although I was able to push a new commit to master, `apm publish` did not work for me. Not sure why:
```
apm publish 0.1.9
Preparing and tagging a new version ✓
Pushing v0.1.9 tag Username for 'https://github.com': kachkaev
Password for 'https://kachkaev@github.com': 
✗
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/cliffrowley/atom-open-in-sourcetree/'
```
Could be to do with my github ssh/2fa setup, will check now.

**Comment by kachkaev** [comment]
OK, finally got this sorted 😅  Tuned out I needed to authenticate with a new [github access token](https://github.com/settings/tokens/) instead of my password because of 2FA. Got too eased off by ssh auth as a default method, so completely forgot how to do this via good old HTTPS 😃 

HTTPS was forced by `apm publish` despite that remote is `git@github.com/...` because `https://..` repo url [is used](https://github.com/cliffrowley/atom-open-in-sourcetree/blob/d2801ef6ad0d1eb0714581f0d04720e54ea46d33/package.json#L12) in package.json.

0.1.9 is out!

**Comment by cliffrowley** [comment]
Excellent, glad you got it sorted - sorry I've been a tad busy!
