### ISSUE TITLE
spaces in file path

### ISSUE THREAD

**Issue by debugDS** [cliffrowley/atom-open-in-sourcetree#2]
If a space is present in file path => no go
I added '...'
line 9 in open-in-sourcetree.coffee
exec "open -a /Applications/SourceTree.app '#{path}'" if path?

Tx

**Comment by cliffrowley** [comment]
Thanks for this, I tend to not use spaces in my source code path names so I guess I missed this!  FYI I'm happy to accept pull requests ;-)
