### ISSUE TITLE
does this support windows?

### ISSUE THREAD

**Issue by mark-hahn** [cliffrowley/atom-open-in-sourcetree#3]
I'm on windows 8.1 and the command doesn't seem to do anything.  If it is mac-only this should probably say so in the readme to save other people of installing and trying this.

**Comment by cliffrowley** [comment]
I would like it to support Windows, but I'm a Mac user myself.  To be fair I created this package when Atom was Mac only - I will update the README for now and then perhaps add Windows support later.  I'm also happy to accept a pull request :-)

**Comment by mark-hahn** [comment]
Maybe I'll do a PR.  I'd really like to have this.

**Comment by cliffrowley** [comment]
@mark-hahn that would be awesome.  I'm also happy to give you collaborator access as it makes sense to have someone on both platforms (e.g. I wouldn't notice if something got inexplicably broken on Windows).

**Comment by mark-hahn** [comment]
No need.  I will let you know if it breaks.  It should always work on
windows when it works on mac if I put in the right windows command.

**Comment by cliffrowley** [comment]
Sure.  I'm pretty busy so if you find I'm not responsive feel free to change your mind ;-)=

**Comment by mark-hahn** [comment]
You were responsive this time.  :-)

**Comment by cliffrowley** [comment]
You got lucky! :-P

**Comment by cliffrowley** [comment]
@mark-hahn I've integrated your pull request and I've pushed the amendments to the master branch.  I haven't released it yet because there are a couple of changes I need to make first (doing so now).  Won't be long and I'll publish.

**Comment by cliffrowley** [comment]
Changes done, but I haven't had a chance to test it on Windows yet.  If you get a chance to do it before me, please let me know and I'll close this issue :-)

**Comment by mark-hahn** [comment]
I'm sorry, but I have managed to rid myself of all windows (yahoo).

**Comment by cliffrowley** [comment]
Hah good on you ;-)

**Comment by cliffrowley** [comment]
Enhancement added as issue https://github.com/cliffrowley/atom-open-in-sourcetree/issues/13
